/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#ffc2c4",
        "surface-dim": "#131313",
        "primary-fixed-dim": "#7bd0ff",
        "tertiary-container": "#30c88f",
        "inverse-primary": "#00668a",
        "on-tertiary-container": "#004e34",
        "surface": "#131313",
        "surface-variant": "#353534",
        "surface-tint": "#7bd0ff",
        "secondary": "#ffb2b7",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#004c69",
        "slate-surface": "#1E293B",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary": "#56e5a9",
        "primary-fixed": "#c4e7ff",
        "on-primary": "#00354a",
        "on-primary-container": "#004965",
        "secondary-fixed": "#ffdadb",
        "on-primary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed": "#40000d",
        "matrix-green": "#10B981",
        "void-black": "#0D0D0D",
        "inverse-on-surface": "#313030",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed": "#6ffbbe",
        "surface-container": "#201f1f",
        "secondary-container": "#b50036",
        "primary": "#8ed5ff",
        "on-surface-variant": "#bdc8d1",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "neon-blue": "#38BDF8",
        "on-secondary-fixed-variant": "#92002a",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#002113",
        "surface-bright": "#3a3939",
        "primary-container": "#38bdf8",
        "surface-container-lowest": "#0e0e0e",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "outline-variant": "#3e484f",
        "on-surface": "#e5e2e1",
        "outline": "#87929a",
        "cyber-pink": "#F43F5E",
        "glass-border": "rgba(255, 255, 255, 0.1)",
        "on-secondary": "#67001b",
        "background": "#131313",
        "on-tertiary": "#003824",
        "secondary-fixed-dim": "#ffb2b7",
        "on-background": "#e5e2e1"
      },
      spacing: {
        "unit": "4px",
        "container-padding": "16px",
        "stack-md": "16px",
        "panel-gap": "8px",
        "gutter": "12px",
        "stack-xs": "4px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}